import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class Login extends javax.swing.JFrame {

 
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setImage();
        // Debug - check resource URL

        getRootPane().setDefaultButton(LoginButton);
        InputPassword.addActionListener(e -> LoginButton.doClick());
        Dimension fixedSize = new Dimension(30, 30);
showPasswordToggle.setPreferredSize(fixedSize);
showPasswordToggle.setMinimumSize(fixedSize);
showPasswordToggle.setMaximumSize(fixedSize);
Icon eyeIcon = getScaledIcon("/images/oeye.png", 20, 20);
Icon eyeoffIcon = getScaledIcon("/images/offeye.png", 20, 20);
      showPasswordToggle.setIcon(eyeoffIcon);
         
Icon arorIcon = getScaledIcon("/images/aror.png", 80, 80);

showPasswordToggle.setPreferredSize(new Dimension(30, 30));
showPasswordToggle.setFocusable(false);
showPasswordToggle.setBorderPainted(false);
showPasswordToggle.setContentAreaFilled(false);
  showPasswordToggle.addActionListener(e -> {
    if (showPasswordToggle.isSelected()) {
        InputPassword.setEchoChar((char) 0);  // Show password
        showPasswordToggle.setIcon(eyeIcon);
    } else {
        InputPassword.setEchoChar('*');       // Hide password
        showPasswordToggle.setIcon(eyeoffIcon);
    }
});
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EmailTitle = new javax.swing.JLabel();
        PasswordTitle = new javax.swing.JLabel();
        InputPassword = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        InputEmail = new javax.swing.JFormattedTextField();
        showPasswordToggle = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        logolabel = new javax.swing.JLabel();
        saplogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        homelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(250, 110));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(204, 204, 204));
        logo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        logo.setMaximumSize(new java.awt.Dimension(800, 400));
        logo.setPreferredSize(new java.awt.Dimension(720, 390));
        logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setText("           LOGIN");
        jLabel1.setAlignmentX(60.0F);
        jLabel1.setAlignmentY(40.0F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 190, 350, 70));

        EmailTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmailTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmailTitle.setText("ENTER EMAIL :");
        EmailTitle.setEnabled(false);
        EmailTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        logo.add(EmailTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 100, 20));

        PasswordTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PasswordTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PasswordTitle.setText("ENTER PASSWORD :");
        PasswordTitle.setEnabled(false);
        PasswordTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        logo.add(PasswordTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 160, 20));

        InputPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        InputPassword.setText("enter password");
        InputPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        InputPassword.setMaximumSize(new java.awt.Dimension(64, 22));
        InputPassword.setPreferredSize(new java.awt.Dimension(64, 22));
        InputPassword.setSelectionColor(java.awt.SystemColor.activeCaptionBorder);
        InputPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputPasswordFocusLost(evt);
            }
        });
        InputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPasswordActionPerformed(evt);
            }
        });
        logo.add(InputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 200, 30));

        LoginButton.setBackground(new java.awt.Color(204, 204, 204));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoginButton.setText("LOGIN");
        LoginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        logo.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 100, 30));

        InputEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        InputEmail.setText("ABCD@aror.edu.pk");
        InputEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        InputEmail.setMaximumSize(new java.awt.Dimension(64, 22));
        InputEmail.setPreferredSize(new java.awt.Dimension(66, 22));
        InputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmailActionPerformed(evt);
            }
        });
        logo.add(InputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 200, 30));

        showPasswordToggle.setBackground(new java.awt.Color(204, 204, 204));
        showPasswordToggle.setFont(new java.awt.Font("Segoe UI", 1, 5)); // NOI18N
        showPasswordToggle.setForeground(new java.awt.Color(0, 0, 51));
        showPasswordToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/offeye.png"))); // NOI18N
        showPasswordToggle.setActionCommand("***\n *\n\n");
        showPasswordToggle.setBorder(null);
        showPasswordToggle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPasswordToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordToggleActionPerformed(evt);
            }
        });
        logo.add(showPasswordToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 30, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("CopyRight: Arorians");
        jLabel3.setEnabled(false);
        jLabel3.setRequestFocusEnabled(false);
        logo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 120, 30));
        logo.add(logolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, 140));
        logo.add(saplogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 40, 30));

        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 540));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homelabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        homelabel.setAlignmentX(200.0F);
        homelabel.setAlignmentY(100.0F);
        homelabel.setAutoscrolls(true);
        homelabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        homelabel.setEnabled(false);
        homelabel.setFocusable(false);
        homelabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homelabel.setIconTextGap(0);
        homelabel.setInheritsPopupMenu(false);
        homelabel.setMaximumSize(new java.awt.Dimension(500, 400));
        homelabel.setMinimumSize(new java.awt.Dimension(0, 0));
        homelabel.setRequestFocusEnabled(false);
        homelabel.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(homelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 540));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 860, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setImage(){
        URL u1 = getClass().getResource("/images/aror1.png");
URL u2 = getClass().getResource("/images/home_logo.png");
URL u3 = getClass().getResource("/images/sap.jpeg");

System.out.println("Logo URL: " + u1);
System.out.println("Home URL: " + u2);
System.out.println("SAP URL: " + u3);
      ImageIcon iconlogo= new ImageIcon(getClass().getResource("/images/aror1.png"));
      ImageIcon iconhomepage= new ImageIcon(getClass().getResource("/images/home_logo.png"));
      ImageIcon iconsap= new ImageIcon(getClass().getResource("/images/sap.jpeg"));

      Image img =iconlogo.getImage().getScaledInstance(logolabel.getWidth(), logolabel.getHeight(), Image.SCALE_SMOOTH);
 Image imghomepage =iconhomepage.getImage().getScaledInstance(homelabel.getWidth(), homelabel.getHeight(), Image.SCALE_SMOOTH);
 Image imglogo =iconsap.getImage().getScaledInstance(saplogo.getWidth(), saplogo.getHeight(), Image.SCALE_SMOOTH);
 
 homelabel.setIcon(new ImageIcon(imghomepage));
 logolabel.setIcon(new ImageIcon(img));
 saplogo.setIcon(new ImageIcon(imglogo));   

    }
    private void InputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPasswordActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_InputPasswordActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
String enteredemail = InputEmail.getText().trim();
String email = enteredemail.toLowerCase().trim();

String password = new String(InputPassword.getPassword()).trim();

        // JPasswordField uses getPassword() which returns a char array for security, 
        // convert it to String for comparison/storage.
      InputEmail.setText("ABCD@aror.edu.pk");
      InputPassword.setText("enter password");  
      final String PLACEHOLDER_TEXT = "ABCD@aror.edu.pk"; // Placeholder ka lowercase version
    
    boolean isValid = true;
    
    // Check 1: Agar user ne sirf placeholder chhor diya hai
    if (enteredemail.equalsIgnoreCase(PLACEHOLDER_TEXT) || enteredemail.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
                                      "Please enter your actual email address. The text shown is only a placeholder.", 
                                      "Validation Error", 
                                      JOptionPane.ERROR_MESSAGE);
        isValid = false;
    }

       String emailRegex= "^[A-Za-z0-9._%+-]+@aror\\.(edu|edi)\\.pk$";
       if(!email.matches(emailRegex)){
           JOptionPane.showMessageDialog(this,"Invalid Email Format.Email must be in this Format like 'Example@aror.edu.pk'.","Validation Error",JOptionPane.ERROR_MESSAGE);
       isValid=false;
       }
       if(password.length() < 6){
        JOptionPane.showMessageDialog(this,"Invalid Password length.Password must be greater than 5","Validation Error",JOptionPane.ERROR_MESSAGE);
       isValid=false;
       }
           Connection con = null;
  
    
        try { 
            con = DBConnect.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    boolean userFound = false;

    // --- TEACHER CHECK ---
    String teacherQuery = "SELECT * FROM teachers WHERE Emails = ? AND Passwords = ?";
    try (PreparedStatement psTeacher = con.prepareStatement(teacherQuery)) {
        psTeacher.setString(1, email);
        psTeacher.setString(2, password);
        try (ResultSet rsTeacher = psTeacher.executeQuery()) {
            if (rsTeacher.next()) {
                userFound = true;
                TeacherInterface teacher = new TeacherInterface(email);
                teacher.setVisible(true);
                this.dispose();
                return;
            }
        }
    }
    catch(Exception e){}
    // --- STUDENT CHECK ---
// --- STUDENT CHECK ---
// --- STUDENT CHECK ---
if (!userFound) {
    Connection studentCon = null;
    try {
        // connect to the students/auth DB (use the correct DB connect class)
        studentCon = DBConnect.getConnection(); // or DBConnect.getConnection() if unified

        String studentQuery = "SELECT * FROM students WHERE Emails = ? AND Passwords = ?";
        try (PreparedStatement psStudent = studentCon.prepareStatement(studentQuery)) {
            psStudent.setString(1, email);       // email already lowercased
            psStudent.setString(2, password);    // password as entered

            try (ResultSet rsStudent = psStudent.executeQuery()) {
                if (rsStudent.next()) {
                    userFound = true;

                    // 1) Validate password format: must be 6 digits
                    if (password == null || password.length()!=6) {
                        JOptionPane.showMessageDialog(this,
                            "Student password must be exactly 6 digits.",
                            "Validation Error",
                            JOptionPane.WARNING_MESSAGE);
                        return;
                    }

                    // 2) Build the SAP from first 3 digits of password
                    String firstThree = password.substring(3, 6);          // e.g. "123"
                    String generatedSap = "5000000" + firstThree;         // e.g. "5000000123"

                    // 3) Optional: if you still need to validate email prefix <-> Roll_No
                    //    fetch dbRoll if you want to keep the previous check:
                    String dbRoll = null;
                    try {
                        dbRoll = rsStudent.getString("Roll_No"); // may be null if column absent
                    } catch (Exception ex) {
                        dbRoll = null;
                    }

                    if (dbRoll != null && !dbRoll.trim().isEmpty()) {
                        String dbRollNorm = dbRoll.replace("-", "").replace("_", "").replace(" ", "").toUpperCase();
                        String emailPrefix = email.split("@")[0].replace("-", "").replace("_", "").replace(" ", "").toUpperCase();

                        if (!dbRollNorm.equalsIgnoreCase(emailPrefix)) {
                            JOptionPane.showMessageDialog(this,
                                "Access Denied! Your email prefix doesn't match registered Roll_No.",
                                "Validation Error",
                                JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                    }
                    // 4) Everything OK — open StudentInterface and pass generatedSap (and email if you want)
                    StudentInterface si = new StudentInterface(email, generatedSap);
                    si.setVisible(true);
                    this.dispose();
                    return;
                }
            }
        }

    } catch (ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(this, "Student DB Driver Missing!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Student Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        if (studentCon != null) {
            try { studentCon.close(); } catch (SQLException e) {}
        }
    }
}

    
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void InputPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPasswordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPasswordFocusGained

    private void InputPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPasswordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPasswordFocusLost

    private void showPasswordToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordToggleActionPerformed
        // TODO add your handling code here:
/*        javax.swing.AbstractButton toggleButton = (javax.swing.AbstractButton) evt.getSource();
  if (toggleButton.isSelected()) {
        InputPassword.setEchoChar((char) 0);  // Show password
        toggleButton.setIcon(eyeIcon);
    } else {
        InputPassword.setEchoChar('*');       // Hide password
        toggleButton.setIcon(eyeoffIcon);
    }
        // isSelected() method JToggleButton aur JCheckBox dono mein kaam karta hai.
  */ 
    }//GEN-LAST:event_showPasswordToggleActionPerformed

    private void InputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmailActionPerformed
private ImageIcon getScaledIcon(String path, int width, int height) {
    try {
        BufferedImage img = ImageIO.read(getClass().getResource(path));

        BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);

        Graphics2D g2 = resized.createGraphics();

        // High quality rendering
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2.drawImage(img, 0, 0, width, height, null);
        g2.dispose();

        return new ImageIcon(resized);

    } catch (Exception e) {
        e.printStackTrace();
        return null;
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailTitle;
    private javax.swing.JFormattedTextField InputEmail;
    private javax.swing.JPasswordField InputPassword;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel PasswordTitle;
    private javax.swing.JLabel homelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel logo;
    private javax.swing.JLabel logolabel;
    private javax.swing.JLabel saplogo;
    private javax.swing.JToggleButton showPasswordToggle;
    // End of variables declaration//GEN-END:variables
    }
