/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
import javax.swing.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.tool.xml.XMLWorkerHelper;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
/**
 *
 * @author KABIR BALOCH
 */
public class StudentInterface extends javax.swing.JFrame {
 private  String loggedEmail ;
    private  String generatedSap ;
    String Name;
String rollNo ;
    String section ;
    String building ;
    String room ;
    String seat ;
    String arrangedBy;
  
    public StudentInterface(String email, String generatedSap) {
        this.loggedEmail = email;
        this.generatedSap = generatedSap;
        initComponents();
                InputStudentSap.addActionListener(e -> SearchButton.doClick());
        // optionally immediately load seat info using generatedSap
        loadSeatUsingSap(generatedSap);
    SetImage();
    }

    private void loadSeatUsingSap(String sap) {
        // your DB lookup code: SELECT * FROM arrangeseats WHERE Sap = ?
        // then show result in outputArea
    }   /**
     * Creates new form StudentInterface
     */
    public StudentInterface() {
        initComponents();
        SetImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        SearchBySingle = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        InputStudentName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        InputStudentSap = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ShowData = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        DownloadButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME TO CHECK SEATING SYSTEM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 9, 700, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 0, 710, 90));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        SearchBySingle.setBackground(new java.awt.Color(153, 153, 153));
        SearchBySingle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Enter  FullName :");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchBySingle.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 59));

        InputStudentName.setBackground(new java.awt.Color(204, 204, 204));
        InputStudentName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        InputStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputStudentNameActionPerformed(evt);
            }
        });
        SearchBySingle.add(InputStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 150, 40));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Enter Sap_ID :");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchBySingle.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, 50));

        InputStudentSap.setBackground(new java.awt.Color(204, 204, 204));
        InputStudentSap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        InputStudentSap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputStudentSapActionPerformed(evt);
            }
        });
        SearchBySingle.add(InputStudentSap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 150, 40));

        SearchButton.setBackground(new java.awt.Color(153, 153, 153));
        SearchButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SearchButton.setText("SEARCH");
        SearchButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        SearchBySingle.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 130, 70));

        ShowData.setEditable(false);
        ShowData.setBackground(new java.awt.Color(204, 204, 204));
        ShowData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ShowData.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(ShowData);

        SearchBySingle.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 390, 220));

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel10.setText("Here is your Data :");
        SearchBySingle.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, -10, 190, 60));

        DownloadButton.setBackground(new java.awt.Color(153, 153, 153));
        DownloadButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        DownloadButton.setText("Download Slip");
        DownloadButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        DownloadButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DownloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadButtonActionPerformed(evt);
            }
        });
        SearchBySingle.add(DownloadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 130, 40));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("LOG OUT");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        SearchBySingle.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 100, 40));

        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchBySingle.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 50, 40));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SearchBySingle, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SearchBySingle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, 860, -1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 93));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void SetImage(){
        ImageIcon icon= new ImageIcon(getClass().getResource("/images/s1.png"));

Image img =icon.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
   jLabel1.setIcon(new ImageIcon(img));
   
ImageIcon icon1= new ImageIcon(getClass().getResource("/images/sap.jpeg"));
Image img1 =icon1.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
   jLabel4.setIcon(new ImageIcon(img1));
   

    }
    private void InputStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputStudentNameActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        
        String fullName = InputStudentName.getText().trim();
        String sapId = InputStudentSap.getText().trim();

        // Step 2: Validate inputs
        if (fullName.isEmpty() || sapId.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please fill in both Full Name and SAP ID fields.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            return; // Stop here
        }
        if (!sapId.equals(generatedSap)) {
    JOptionPane.showMessageDialog(this,
        "You can only check your own data. The SAP you entered does not match your login.",
        "Access Denied",
        JOptionPane.ERROR_MESSAGE);
    return;
}
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/arrangeseats_database", "root", "");

            // Step 3: SQL Query
            String sql = "SELECT Name,Room,Roll_No,Section,Building ,SeatNo,ArrangedBy FROM arrangedseats WHERE Name = ? AND Sap = ? ";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, fullName);
            pst.setString(2, sapId);
            ResultSet rs = pst.executeQuery();

            // Step 4: Show Data
           if (rs.next()) {
    Name = rs.getString("Name");
    
    rollNo = rs.getString("Roll_No");
     section = rs.getString("Section");
     building = rs.getString("Building");
     room = rs.getString("Room");
     seat = rs.getString("SeatNo");
     arrangedBy = rs.getString("ArrangedBy");

    ShowData.setContentType("text/html");

    ShowData.setText(
        "<html>"
        + "<div style='border:2px solid black; padding:18px; width:280px; font-family:Segoe UI; font-size:13px;'>"
        + "<h3 style='text-align:center; margin:0;'>EXAM ADMIT SLIP</h3>"
        + "<hr>"

        + "<p><b>Name:</b> " + Name + "</p>"
        + "<p><b>Roll No:</b> " + rollNo + "</p>"
        + "<p><b>SAP ID:</b> " + sapId + "</p>"
        + "<p><b>Section:</b> " + section + "</p>"
        + "<hr>"

        + "<p><b>Building:</b> " + building + "</p>"
        + "<p><b>Room:</b> " + room + "</p>"
        + "<p><b>Seat No:</b> " + seat + "</p>"
        + "<hr>"

        + "<p><b>Arranged By:</b> " + arrangedBy + "</p>"
        + "<p style='text-align:center; font-size:11px; margin-top:10px;'>Must bring University ID & CNIC</p>"
        + "</div>"
        + "</html>"
    );
}
 else {
                JOptionPane.showMessageDialog(this, "No record found for this student.");
            }

            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void generatePDF() {
    try {
        // Get student info from your fields or text area
        String fullName = InputStudentName.getText().trim();
        String sapId = InputStudentSap.getText().trim();
        String slipText = ShowData.getText().trim(); // optional if you want preformatted text

        if (fullName.isEmpty() || sapId.isEmpty() || slipText.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter/search student data before generating PDF.");
            return;
        }

        // Build HTML dynamically
        String html = "<html><body style='font-family: Arial; text-align: center;'>"
                + "<div style='border:2px solid black; padding:18px; width:300px; margin:auto;'>"
                + "<h3 style='margin:0;'>EXAM ADMIT SLIP</h3>"
                + "<hr style='border:1px solid black;'/>"
                + "<p><b>Name:</b> " + Name + "</p>"
                + "<p><b>Roll No:</b> " + rollNo + "</p>"
                + "<p><b>SAP ID:</b> " + sapId + "</p>"
                + "<p><b>Section:</b> " + section + "</p>"
                + "<hr style='border:1px solid black;'/>"
                + "<p><b>Building:</b> " + building + "</p>"
                + "<p><b>Room:</b> " + room + "</p>"
                + "<p><b>Seat No:</b> " + seat + "</p>"
                + "<hr style='border:1px solid black;'/>"
                + "<p><b>Arranged By:</b> " + arrangedBy + "</p>"
                + "<p style='margin-top:10px;'><b>Must bring University ID &amp; CNIC</b></p>"
                + "</div></body></html>";

        // Save PDF to Desktop
String savePath = "C:\\Users\\KABIR BALOCH\\OneDrive\\Documents\\NetBeansProjects\\StudentExamSeatingSystem\\5000000311-KabeerAhmed-ExamSeatArrangementSystem\\Slips";
String fileName = savePath + fullName.replaceAll("\\s+", "_") + "_AdmitSlip.pdf";

        Document document = new Document(PageSize.A4, 50, 50, 50, 50);
        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(fileName));
        document.open();

        InputStream is = new ByteArrayInputStream(html.getBytes("UTF-8"));
        XMLWorkerHelper.getInstance().parseXHtml(writer, document, is);

        document.close();
        JOptionPane.showMessageDialog(this, "PDF Saved on :\n" + fileName);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error generating PDF: " + e.getMessage());
    }
}

    private void InputStudentSapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputStudentSapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputStudentSapActionPerformed

    private void DownloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownloadButtonActionPerformed
        // TODO add your handling code here:
        generatePDF();
    }//GEN-LAST:event_DownloadButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DownloadButton;
    private javax.swing.JTextField InputStudentName;
    private javax.swing.JTextField InputStudentSap;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel SearchBySingle;
    private javax.swing.JTextPane ShowData;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
